version: 1
metadata:
  name: nAI Backend OAuth2 Application - Fixed
  labels:
    blueprints.goauthentik.io/description: OAuth2 Provider and Application for nAI Backend (Fixed)
entries:
  # OAuth2 Provider for Backend
  - model: authentik_providers_oauth2.oauth2provider
    state: present
    id: provider-nai-backend-fixed
    identifiers:
      name: nAI Backend Provider
    attrs:
      name: nAI Backend Provider
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
      client_type: confidential
      client_id: nai-backend
      client_secret: !Env AUTHENTIK_BACKEND_CLIENT_SECRET
      redirect_uris: |
        http://localhost:8000/api/v1/auth/callback
        http://localhost:8000/api/v1/docs/oauth2-redirect
        http://localhost:3000/callback
      authorization_grant_type:
        - authorization_code
        - refresh_token
        - client_credentials
        - password
      sub_mode: hashed_user_id
      include_claims_in_id_token: true
      issuer_mode: per_provider
      access_code_validity: minutes=1
      access_token_validity: hours=24
      refresh_token_validity: days=30
      # Property mappings
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]

  # Application for Backend
  - model: authentik_core.application
    state: present
    id: app-nai-backend-fixed
    identifiers:
      slug: nai-backend
    attrs:
      name: nAI Backend
      slug: nai-backend
      provider: !KeyOf provider-nai-backend-fixed
      meta_launch_url: http://localhost:8000
      meta_description: nAI Backend API Service
      policy_engine_mode: any
