version: 1
metadata:
  name: nAI Frontend OAuth2 - Public Client
  labels:
    blueprints.goauthentik.io/description: OAuth2 Provider for frontend SPA (public client)
entries:
  # OAuth2 Provider for Frontend - Public Client
  - model: authentik_providers_oauth2.oauth2provider
    state: present
    id: provider-nai-frontend-public
    identifiers:
      name: nAI Frontend Provider
    attrs:
      name: nAI Frontend Provider
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
      client_type: public  # Public client for SPA
      client_id: nai-frontend
      redirect_uris: |
        http://localhost:3000/callback
        http://localhost:3000/auth/callback
        http://localhost:3001/callback
        http://localhost:3001/auth/callback
        http://localhost:5173/callback
        http://localhost:5173/auth/callback
        http://localhost:8000/api/v1/docs/oauth2-redirect
      authorization_grant_type:
        - authorization_code
        - refresh_token
      sub_mode: hashed_user_id
      include_claims_in_id_token: true
      issuer_mode: per_provider
      access_code_validity: minutes=1
      access_token_validity: hours=8
      refresh_token_validity: days=7
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]

  # Application for Frontend
  - model: authentik_core.application
    state: present
    id: app-nai-frontend-public
    identifiers:
      slug: nai-frontend
    attrs:
      name: nAI Frontend
      slug: nai-frontend
      provider: !KeyOf provider-nai-frontend-public
      meta_launch_url: http://localhost:3000
      meta_description: nAI Frontend Application
      policy_engine_mode: any
