version: 1
metadata:
  name: nAI Backend OAuth2 - Development
  labels:
    blueprints.goauthentik.io/description: OAuth2 Provider for development with permissive redirects
entries:
  # OAuth2 Provider for Backend - Development
  - model: authentik_providers_oauth2.oauth2provider
    state: present
    id: provider-nai-backend-dev
    identifiers:
      name: nAI Backend Provider Dev
    attrs:
      name: nAI Backend Provider Dev
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
      client_type: confidential
      client_id: nai-backend-dev
      client_secret: !Env AUTHENTIK_BACKEND_CLIENT_SECRET
      # Permissive redirect URIs for development
      # Covers common development ports and patterns
      redirect_uris: |
        http://localhost:3000/callback
        http://localhost:3000/auth/callback
        http://localhost:3000/api/auth/callback
        http://localhost:3001/callback
        http://localhost:3001/auth/callback
        http://localhost:3001/api/auth/callback
        http://localhost:4200/callback
        http://localhost:4200/auth/callback
        http://localhost:5000/callback
        http://localhost:5000/auth/callback
        http://localhost:5173/callback
        http://localhost:5173/auth/callback
        http://localhost:5174/callback
        http://localhost:5174/auth/callback
        http://localhost:8000/api/v1/auth/callback
        http://localhost:8000/api/v1/docs/oauth2-redirect
        http://localhost:8080/callback
        http://localhost:8080/auth/callback
        http://127.0.0.1:3000/callback
        http://127.0.0.1:3000/auth/callback
        http://127.0.0.1:8000/api/v1/auth/callback
        http://127.0.0.1:8000/api/v1/docs/oauth2-redirect
      authorization_grant_type:
        - authorization_code
        - refresh_token
        - client_credentials
        - password
        - implicit  # For development/testing
      sub_mode: hashed_user_id
      include_claims_in_id_token: true
      issuer_mode: per_provider
      access_code_validity: minutes=1
      access_token_validity: hours=24
      refresh_token_validity: days=30
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]

  # Application for Backend - Development
  - model: authentik_core.application
    state: present
    id: app-nai-backend-dev
    identifiers:
      slug: nai-backend-dev
    attrs:
      name: nAI Backend (Development)
      slug: nai-backend-dev
      provider: !KeyOf provider-nai-backend-dev
      meta_launch_url: http://localhost:8000
      meta_description: nAI Backend API Service (Development)
      policy_engine_mode: any
