version: 1
metadata:
  name: nAI Frontend OAuth2 Application
  labels:
    blueprints.goauthentik.io/description: OAuth2 Provider and Application for nAI Frontend
entries:
  # OAuth2 Provider für Frontend
  - model: authentik_providers_oauth2.oauth2provider
    state: present
    id: provider-nai-frontend
    identifiers:
      name: nAI Frontend Provider
    attrs:
      name: nAI Frontend Provider
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
      client_type: public  # Frontend ist public client (SPA)
      client_id: nai-frontend
      # Public clients haben kein Client Secret
      redirect_uris: |
        http://127.0.0.1:3000/auth/callback
        http://127.0.0.1:3000/api/auth/callback/authentik
        http://127.0.0.1:3001/auth/callback
        http://127.0.0.1:3001/api/auth/callback/authentik
        http://localhost:3000/auth/callback
        http://localhost:3000/api/auth/callback/authentik
        http://localhost:3001/auth/callback
        http://localhost:3001/api/auth/callback/authentik
      # PKCE für public clients
      sub_mode: hashed_user_id
      include_claims_in_id_token: true
      issuer_mode: per_provider
      # JWT Signing
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, "authentik Self-signed Certificate"]]
      # Token Gültigkeit für Frontend (kürzer als Backend)
      access_code_validity: minutes=1
      access_token_validity: hours=8
      refresh_token_validity: days=7
      # Scopes
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-email]]
        - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-profile]]

  # Application für Frontend
  - model: authentik_core.application
    state: present
    id: app-nai-frontend
    identifiers:
      slug: nai-frontend
    attrs:
      name: nAI Frontend
      slug: nai-frontend
      provider: !KeyOf provider-nai-frontend
      meta_launch_url: http://127.0.0.1:3000
      meta_icon: https://goauthentik.io/img/icon.png
      meta_description: nAI Frontend Web Application
      # Öffentlicher Zugriff für alle authentifizierten Benutzer
      policy_engine_mode: any
      open_in_new_tab: true

  # Gruppe für Frontend-Benutzer
  - model: authentik_core.group
    state: present
    id: group-nai-users
    identifiers:
      name: nAI Users
    attrs:
      name: nAI Users

  # Standard-Benutzer für Tests (optional)
  - model: authentik_core.user
    state: present
    id: user-test
    identifiers:
      username: testuser
    attrs:
      username: testuser
      email: test@example.com
      name: Test User
      password: !Env [TEST_USER_PASSWORD, "testpassword123"]
      groups:
        - !KeyOf group-nai-users
