"""Add sequence_number to messages

Revision ID: 7a44543fbf7f
Revises: 9c9483fa7130
Create Date: 2025-06-23 17:00:54.109699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a44543fbf7f'
down_revision: Union[str, None] = '9c9483fa7130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sequence_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sequence_number')
    # ### end Alembic commands ###